nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['http://localhost:3000']  # Reemplaza con tu frontend si está en otro dominio
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600

    paths:
        '^/': null
